name: Bundle with PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUNDLE_NAME: imz

jobs:
  build:
    name: Bundle scripts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Bundle with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --add-data "README.md;README.md" run.py
    - name: Bundle with PyInstaller (Linux, macOS)
      if: runner.os != 'Windows'
      run: |
        pyinstaller --onefile --add-data "README.md:README.md" run.py
