name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: action-test
  ARCHIVE_NAME: action-test-${{ github.run_number }}.tar.gz

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: |
        echo IMAGE_NAME=${IMAGE_NAME}
        echo VERSION=${{ github.run_number }}
        docker build --file Dockerfile --tag ${IMAGE_NAME}:${{ github.run_number }} --tag ${IMAGE_NAME}:latest .
    
    - name: Save the image to a tar.gz archive
      run: docker save ${IMAGE_NAME} | gzip > ${ARCHIVE_NAME}
    
    - name: Upload the archive
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ${{ env.ARCHIVE_NAME }}